- name: Setup Deno environment
  uses: denolib/setup-deno@v2.0.0
  with:
    # Version range or exact version of a Deno version to use.
    deno-version: 1.1.3
     
- name: Bundle and zip Deno app
      run:deno bundle server.ts server.bundle.js zip app.zip server.bundle.js

- name: Azure Login
  uses: Azure/login@v1.1
  with: creds:${{ secrets.AZURE_CREDENTIALS }}

- name: Deploy Deno to Azure App Service 
  uses: anthonychu/azure-webapps-deno-deploy@v0.3.0      
  with:     
   # Name of the Azure Web App 
    app-name: deno-pruebaazure
   # Name of the resource group  
    resource-group: denoprueba1
    # Path to zip package to deploy 
    package: app.zip        
    script-file: server.bundle.js        
   # Version of deno to use
      deno-version: 1.1.3
